# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Vk1Rboag6UUsoZsabxTXsIhjSN0JSyi
"""

languages = {'Python':88, 'Java':87, 'C': 86, 'C++' :85, '.Net':19}
 
Keymax = max(languages, key= lambda x: languages[x])
print(Keymax)

