# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vs9nycogOeL2ve9Y-yzdyNJ_pmlJ2SgU

Python Zero to Hero Batch Assignment Number 01 
Assignment 01: Take multiple numbers through input and print the sum of the numbers.
"""

a = int(input('Please Enter First number for Sum:-'))
b = int(input('Please Enter Second number for Sum:-'))

print('Performing Additions please wait')
sum = a + b
print('*********************************')
print('the Sum is :-', (sum))